#!/usr/bin/env python3
"""gen_descriptor.py — emit the mcpp-index compat.ffmpeg.lua descriptor.

Inputs are the products of one hermetic configure run made from the OFFICIAL
release tarball (tools/gen_config.sh logic, out-of-tree):

  <builddir>/config.h, config_components.h, config.asm, config_components.asm
  <builddir>/libavutil/{avconfig.h, ffversion.h}
  <builddir>/lib{avcodec,avformat,avfilter,avdevice}/*_list.c
  <builddir>/sources.txt            (make -n derivation, `src/...` prefixed)

The descriptor inlines the config snapshot as `generated_files` (they are
deterministic pure text for a frozen (target, profile)) and the exact source
list, so consumers build FFmpeg from source with zero configure/make at any
point — the compat package is the single source of truth for the recipe.

Usage: gen_descriptor.py <builddir> <version> <sha256> <out.lua>
"""

import sys
from pathlib import Path

GEN_FILES = [
    "config.h",
    "config_components.h",
    "config.asm",
    "config_components.asm",
    "libavutil/avconfig.h",
    "libavutil/ffversion.h",
    "libavcodec/codec_list.c",
    "libavcodec/parser_list.c",
    "libavcodec/bsf_list.c",
    "libavformat/demuxer_list.c",
    "libavformat/muxer_list.c",
    "libavformat/protocol_list.c",
    "libavfilter/filter_list.c",
    "libavdevice/indev_list.c",
    "libavdevice/outdev_list.c",
]

INCLUDE_DIRS = [
    "mcpp_generated",
    "mcpp_generated/libavcodec",
    "mcpp_generated/libavformat",
    "mcpp_generated/libavfilter",
    "mcpp_generated/libavdevice",
    "*",
    # libavcodec root for the sub-Makefile dirs' quote-includes (aac/bsf/hevc/
    # opus/vvc include "mathops.h" etc. from their library root). Safe: no
    # system-header names are shadowed from here.
    "*/libavcodec",
    # NASM receives every include dir automatically (-I), which is how the
    # .asm units find x86inc/x86util and config.asm.
    "*/libavutil/x86",
    "*/libavcodec/x86",
    "*/libavfilter/x86",
    "*/libswscale/x86",
    "*/libswresample/x86",
]

CFLAGS = [
    "-DHAVE_AV_CONFIG_H",
    "-D_ISOC11_SOURCE", "-D_FILE_OFFSET_BITS=64", "-D_LARGEFILE_SOURCE",
    "-D_POSIX_C_SOURCE=200112", "-D_XOPEN_SOURCE=600", "-DPIC",
    "-fomit-frame-pointer", "-fno-math-errno", "-fno-signed-zeros",
    "-pthread", "-w",
]

BUILDING = ["avutil", "avcodec", "avformat", "avfilter", "avdevice",
            "swscale", "swresample"]


def lua_str_list(items, indent):
    pad = " " * indent
    return ("{\n" + "".join(f'{pad}    "{i}",\n' for i in items) + pad + "}")


def main() -> None:
    builddir, version, sha256, out_path = (Path(sys.argv[1]), sys.argv[2],
                                           sys.argv[3], Path(sys.argv[4]))

    sources = ["*/" + line.strip().removeprefix("src/")
               for line in (builddir / "sources.txt").read_text().splitlines()
               if line.strip()]
    n_asm = sum(1 for s in sources if s.endswith(".asm"))

    gen_entries = []
    for rel in GEN_FILES:
        text = (builddir / rel).read_text()
        if "]==]" in text:
            sys.exit(f"gen_descriptor: ']==]' inside {rel} — pick another delimiter")
        gen_entries.append(f'        ["mcpp_generated/{rel}"] = [==[\n{text}]==],')

    flags_entries = [
        f'            {{ glob = "*/lib{lib}/**", defines = {{ "BUILDING_{lib}" }} }},'
        for lib in BUILDING
    ]
    flags_entries.append(
        '            { glob = "**/*.asm", asmflags = { "-Pconfig.asm" } },')

    url_global = f"https://ffmpeg.org/releases/ffmpeg-{version}.tar.gz"
    url_cn = (f"https://gitcode.com/mcpp-res/ffmpeg/releases/download/"
              f"{version}/ffmpeg-{version}.tar.gz")

    lua = f"""-- Auto-generated by tools/compat-ffmpeg/gen_descriptor.py — do not edit by hand.
-- Recipe: FFmpeg {version} built FROM SOURCE by mcpp (no configure/make at
-- build time). Full internal-component hermetic profile, LGPL-2.1+ (configure:
-- --disable-autodetect --disable-programs --disable-doc; everything else
-- default, x86 NASM asm included — {n_asm} .asm units, nasm resolved
-- PATH → sandbox → xlings). The config snapshot below is deterministic for
-- (linux-x86_64, this profile) and shipped as generated_files; the source
-- list is the `make -n` ground truth of the same configure run.
-- Regenerate: sh tools/compat-ffmpeg/gen_config.sh (this repo).
package = {{
    spec        = "1",
    namespace   = "compat",
    name        = "compat.ffmpeg",
    description = "FFmpeg {version} multimedia libraries, full source build (LGPL profile)",
    licenses    = {{"LGPL-2.1-or-later"}},
    repo        = "https://ffmpeg.org",
    type        = "package",

    xpm = {{
        -- linux-x86_64 only for now: the config snapshot + source list are
        -- target-specific; macOS/Windows land with their own snapshots.
        linux = {{
            ["{version}"] = {{
                url    = {{
                    GLOBAL = "{url_global}",
                    CN     = "{url_cn}",
                }},
                sha256 = "{sha256}",
            }},
        }},
    }},

    mcpp = {{
        c_standard   = "c17",
        include_dirs = {lua_str_list(INCLUDE_DIRS, 8)},
        cflags       = {lua_str_list(CFLAGS, 8)},
        flags = {{
{chr(10).join(flags_entries)}
        }},
        targets = {{
            ffmpeg = {{ kind = "lib" }},
        }},
        linux = {{
            ldflags = {{ "-lpthread", "-lm" }},
        }},
        sources = {lua_str_list(sources, 8)},
        generated_files = {{
{chr(10).join(gen_entries)}
        }},
    }},
}}
"""
    out_path.write_text(lua)
    print(f"gen_descriptor: {out_path} written — {len(sources)} sources "
          f"({n_asm} .asm), {len(GEN_FILES)} generated files, "
          f"{len(lua) // 1024} KiB")


if __name__ == "__main__":
    main()
