-- compat.llamacpp — llama.cpp b10069 registry + llama implementation
--
-- 消费者引入:
--     mcpp add compat.llamacpp@b10069
--
-- 拥有 ggml-backend register/dynamic-loader 和 llama 推理实现 + 模型 TU.
-- Metal backend 通过 backend-metal feature 转发, P3 阶段实现.

package = {
    spec        = "1",
    namespace   = "compat",
    name        = "compat.llamacpp",
    description = "llama.cpp b10069 — registry + llama inference",
    licenses    = {"MIT"},
    repo        = "https://github.com/ggml-org/llama.cpp",
    type        = "package",

    xpm = {
        linux = {
            ["b10069"] = {
                url = {
                    GLOBAL = "https://github.com/ggml-org/llama.cpp/archive/refs/tags/b10069.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/llamacpp/releases/download/b10069/llama.cpp-b10069.tar.gz",
                },
                sha256 = "293a7c65a11e2203c5468a06d0d0e8d21dfff16ad08712b16c61efbe0d93e097",
            },
        },
        macosx = {
            ["b10069"] = {
                url = {
                    GLOBAL = "https://github.com/ggml-org/llama.cpp/archive/refs/tags/b10069.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/llamacpp/releases/download/b10069/llama.cpp-b10069.tar.gz",
                },
                sha256 = "293a7c65a11e2203c5468a06d0d0e8d21dfff16ad08712b16c61efbe0d93e097",
            },
        },
        windows = {
            ["b10069"] = {
                url = {
                    GLOBAL = "https://github.com/ggml-org/llama.cpp/archive/refs/tags/b10069.tar.gz",
                    CN     = "https://gitcode.com/mcpp-res/llamacpp/releases/download/b10069/llama.cpp-b10069.tar.gz",
                },
                sha256 = "293a7c65a11e2203c5468a06d0d0e8d21dfff16ad08712b16c61efbe0d93e097",
            },
        },
    },

    mcpp = {
        c_standard  = "c11",
        language    = "c++23",
        import_std  = false,
        include_dirs = {
            "*/include",
            "*/ggml/include",
            "*/ggml/src",
            "*/ggml/src/ggml-cpu",
            "*/src",
        },
        sources = {
            "*/ggml/src/ggml-backend-dl.cpp",
            "*/ggml/src/ggml-backend-reg.cpp",
            "*/src/llama.cpp",
            "*/src/llama-adapter.cpp",
            "*/src/llama-arch.cpp",
            "*/src/llama-batch.cpp",
            "*/src/llama-chat.cpp",
            "*/src/llama-context.cpp",
            "*/src/llama-cparams.cpp",
            "*/src/llama-grammar.cpp",
            "*/src/llama-graph.cpp",
            "*/src/llama-hparams.cpp",
            "*/src/llama-impl.cpp",
            "*/src/llama-io.cpp",
            "*/src/llama-kv-cache.cpp",
            "*/src/llama-kv-cache-iswa.cpp",
            "*/src/llama-kv-cache-dsa.cpp",
            "*/src/llama-kv-cache-dsv4.cpp",
            "*/src/llama-memory.cpp",
            "*/src/llama-memory-hybrid.cpp",
            "*/src/llama-memory-hybrid-iswa.cpp",
            "*/src/llama-memory-recurrent.cpp",
            "*/src/llama-mmap.cpp",
            "*/src/llama-model-loader.cpp",
            "*/src/llama-model-saver.cpp",
            "*/src/llama-model.cpp",
            "*/src/llama-quant.cpp",
            "*/src/llama-sampler.cpp",
            "*/src/llama-vocab.cpp",
            "*/src/unicode-data.cpp",
            "*/src/unicode.cpp",
        "*/models/afmoe.cpp",
        "*/models/apertus.cpp",
        "*/models/arcee.cpp",
        "*/models/arctic.cpp",
        "*/models/arwkv7.cpp",
        "*/models/bailingmoe.cpp",
        "*/models/bailingmoe2.cpp",
        "*/models/bitnet.cpp",
        "*/models/chameleon.cpp",
        "*/models/chatglm.cpp",
        "*/models/codeshell.cpp",
        "*/models/cogvlm.cpp",
        "*/models/cohere2.cpp",
        "*/models/cohere2moe.cpp",
        "*/models/command-r.cpp",
        "*/models/dbrx.cpp",
        "*/models/deepseek.cpp",
        "*/models/deepseek2.cpp",
        "*/models/deepseek2ocr.cpp",
        "*/models/deepseek32.cpp",
        "*/models/deepseek4.cpp",
        "*/models/delta-net-base.cpp",
        "*/models/dflash.cpp",
        "*/models/dots1.cpp",
        "*/models/dream.cpp",
        "*/models/eagle3.cpp",
        "*/models/ernie4-5-moe.cpp",
        "*/models/ernie4-5.cpp",
        "*/models/exaone-moe.cpp",
        "*/models/exaone.cpp",
        "*/models/exaone4.cpp",
        "*/models/falcon-h1.cpp",
        "*/models/gemma-embedding.cpp",
        "*/models/gemma.cpp",
        "*/models/gemma2.cpp",
        "*/models/gemma3.cpp",
        "*/models/gemma3n.cpp",
        "*/models/gemma4-assistant.cpp",
        "*/models/gemma4.cpp",
        "*/models/glm-dsa.cpp",
        "*/models/glm4-moe.cpp",
        "*/models/glm4.cpp",
        "*/models/gpt2.cpp",
        "*/models/gptneox.cpp",
        "*/models/granite-hybrid.cpp",
        "*/models/granite-moe.cpp",
        "*/models/granite.cpp",
        "*/models/grovemoe.cpp",
        "*/models/hunyuan-dense.cpp",
        "*/models/hunyuan-moe.cpp",
        "*/models/hunyuan-vl.cpp",
        "*/models/hy-v3.cpp",
        "*/models/internlm2.cpp",
        "*/models/jais.cpp",
        "*/models/jais2.cpp",
        "*/models/jamba.cpp",
        "*/models/jina-bert-v2.cpp",
        "*/models/jina-bert-v3.cpp",
        "*/models/kimi-linear.cpp",
        "*/models/lfm2.cpp",
        "*/models/lfm2moe.cpp",
        "*/models/llada-moe.cpp",
        "*/models/llada.cpp",
        "*/models/llama-embed.cpp",
        "*/models/mamba-base.cpp",
        "*/models/mamba.cpp",
        "*/models/mamba2.cpp",
        "*/models/mellum.cpp",
        "*/models/mimo2.cpp",
        "*/models/minicpm.cpp",
        "*/models/minicpm3.cpp",
        "*/models/minimax-m2.cpp",
        "*/models/mistral3.cpp",
        "*/models/mistral4.cpp",
        "*/models/modern-bert.cpp",
        "*/models/mpt.cpp",
        "*/models/nemotron-h-moe.cpp",
        "*/models/nemotron-h.cpp",
        "*/models/nemotron.cpp",
        "*/models/neo-bert.cpp",
        "*/models/nomic-bert-moe.cpp",
        "*/models/nomic-bert.cpp",
        "*/models/olmo.cpp",
        "*/models/olmo2.cpp",
        "*/models/olmoe.cpp",
        "*/models/openai-moe.cpp",
        "*/models/openelm.cpp",
        "*/models/orion.cpp",
        "*/models/paddleocr.cpp",
        "*/models/pangu-embed.cpp",
        "*/models/phi2.cpp",
        "*/models/phi3.cpp",
        "*/models/phimoe.cpp",
        "*/models/plamo.cpp",
        "*/models/plamo2.cpp",
        "*/models/plamo3.cpp",
        "*/models/plm.cpp",
        "*/models/qwen.cpp",
        "*/models/qwen2.cpp",
        "*/models/qwen2moe.cpp",
        "*/models/qwen2vl.cpp",
        "*/models/qwen3.cpp",
        "*/models/qwen35.cpp",
        "*/models/qwen35moe.cpp",
        "*/models/qwen3moe.cpp",
        "*/models/qwen3next.cpp",
        "*/models/qwen3vl.cpp",
        "*/models/qwen3vlmoe.cpp",
        "*/models/rnd1.cpp",
        "*/models/rwkv6-base.cpp",
        "*/models/rwkv6.cpp",
        "*/models/rwkv6qwen2.cpp",
        "*/models/rwkv7-base.cpp",
        "*/models/rwkv7.cpp",
        "*/models/seed-oss.cpp",
        "*/models/smallthinker.cpp",
        "*/models/smollm3.cpp",
        "*/models/stablelm.cpp",
        "*/models/starcoder2.cpp",
        "*/models/step35.cpp",
        "*/models/t5.cpp",
        "*/models/t5encoder.cpp",
        "*/models/wavtokenizer-dec.cpp",
        "*/models/xverse.cpp",
        },
        targets = {
            ["llama"] = { kind = "lib" },
        },
        cflags   = { "-w" },
        cxxflags = { "-w" },
        flags = {
            { glob = "*/ggml/src/ggml-backend-reg.cpp", defines = { "GGML_USE_CPU" } },
            { glob = "*/src/models/t5.cpp",      cxxflags = { "-std=c++20" } },
            { glob = "*/src/models/eagle3.cpp",  cxxflags = { "-std=c++20" } },
            { glob = "*/src/models/dflash.cpp",   cxxflags = { "-std=c++20" } },
        },
        deps = {
            ["compat.ggml-base"] = "b10069",
            ["compat.ggml-cpu"]  = "b10069",
        },
        linux = {
            ldflags = { "-ldl" },
        },
        macosx = {
            features = {
                ["backend-metal"] = {
                    deps = {
                        ["compat.ggml-metal"] = "b10069",
                    },
                    requires = { "ggml.accelerator" },
                    flags = {
                        {
                            glob = "*/ggml/src/ggml-backend-reg.cpp",
                            defines = { "GGML_USE_METAL" },
                        },
                    },
                },
            },
        },
    },
}
